"""empty message

Revision ID: 640ec69b3dc5
Revises: 
Create Date: 2025-01-23 20:42:15.101881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640ec69b3dc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
            sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('hashed_psw', sa.String(length=100), nullable=False),
            sa.PrimaryKeyConstraint('auth_id'),
            sa.UniqueConstraint('hashed_psw'),
            sa.UniqueConstraint('username')
    )
    op.create_table('contacts',
            sa.Column('contact_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('telegram', sa.String(length=50), nullable=True),
            sa.Column('email', sa.String(length=50), nullable=True),
            sa.Column('phone', sa.String(length=30), nullable=True),
            sa.Column('other', sa.String(length=30), nullable=True),
            sa.PrimaryKeyConstraint('contact_id'),
            sa.UniqueConstraint('email'),
            sa.UniqueConstraint('other'),
            sa.UniqueConstraint('phone'),
            sa.UniqueConstraint('telegram'),
            sa.UniqueConstraint('username')
    )
    op.create_table('users',
            sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('age', sa.Integer(), nullable=False),
            sa.Column('hobbies', sa.String(length=50), nullable=True),
            sa.Column('bio', sa.String(length=100), nullable=True),
            sa.Column('contact_me', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['contact_me'], ['contacts.username'], ),
            sa.PrimaryKeyConstraint('auth_id'),
            sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('contacts')
    op.drop_table('auth')
    # ### end Alembic commands ###
