"""empty message

Revision ID: 84fdfe75ea85
Revises: 46366fb01814
Create Date: 2025-02-01 13:22:51.418942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fdfe75ea85'
down_revision: Union[str, None] = '46366fb01814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth')
    op.drop_constraint('contacts_telegram_key', 'contacts', type_='unique')
    op.create_index(op.f('ix_contacts_telegram'), 'contacts', ['telegram'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_telegram'), table_name='contacts')
    op.create_unique_constraint('contacts_telegram_key', 'contacts', ['telegram'])
    op.create_table('auth',
    sa.Column('auth_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('hashed_psw', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('auth_id', name='auth_pkey'),
    sa.UniqueConstraint('hashed_psw', name='auth_hashed_psw_key'),
    sa.UniqueConstraint('username', name='auth_username_key')
    )
    # ### end Alembic commands ###
