"""empty message

Revision ID: 0ec7430687dc
Revises: a58c53e531e0
Create Date: 2025-03-05 20:59:34.333142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec7430687dc'
down_revision: Union[str, None] = 'a58c53e531e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_other_key', 'users', type_='unique')
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.drop_index('ix_users_telegram', table_name='users')
    op.create_index(op.f('ix_users_telegram'), 'users', ['telegram'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram'), table_name='users')
    op.create_index('ix_users_telegram', 'users', ['telegram'], unique=True)
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.create_unique_constraint('users_other_key', 'users', ['other'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
