"""empty message

Revision ID: a58c53e531e0
Revises: 
Create Date: 2025-02-21 18:39:40.372477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58c53e531e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
            sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('hashed_psw', sa.String(length=100), nullable=False),
            sa.PrimaryKeyConstraint('auth_id'),
            sa.UniqueConstraint('hashed_psw'),
            sa.UniqueConstraint('username')
    )
    op.create_table('users',
            sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('username', sa.String(length=20), nullable=False),
            sa.Column('age', sa.Integer(), nullable=False),
            sa.Column('hobbies', sa.String(length=50), nullable=True),
            sa.Column('bio', sa.String(length=100), nullable=True),
            sa.Column('telegram', sa.String(length=50), nullable=True),
            sa.Column('email', sa.String(length=50), nullable=True),
            sa.Column('phone', sa.String(length=30), nullable=True),
            sa.Column('other', sa.String(length=100), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.PrimaryKeyConstraint('auth_id'),
            sa.UniqueConstraint('email'),
            sa.UniqueConstraint('other'),
            sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_telegram'), 'users', ['telegram'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_table('users')
    op.drop_table('auth')
    # ### end Alembic commands ###
